# Imagen base de Python
FROM python:3.11-slim

# Crear un directorio de trabajo dentro del contenedor
WORKDIR /code
ENV PYTHONPATH=/code

# Copiar el archivo de requerimientos e instalarlos
COPY requirements-prod.txt .
RUN pip install --no-cache-dir -r requirements-prod.txt

# Copiar el código de la app
COPY ./app /code/app
COPY start-prod.sh /code/start-prod.sh

# Dar permisos de ejecución al script
RUN chmod +x /code/start-prod.sh

ENV PORT=8000
EXPOSE 8000

# Comando por defecto: correr el script de inicio
CMD ["/code/start-prod.sh"]
