[pytest]
# Opciones por defecto
addopts = --verbose
testpaths = tests

# Logs de consola durante la ejecución
log_cli = false
log_cli_level = INFO

# Log de pytest nativo (errores internos del framework, no de los tests)
log_file = tests/logs/pytest_internal.log
log_file_level = WARNING
log_file_format = %(asctime)s [%(levelname)s] %(message)s
log_file_date_format = %Y-%m-%d %H:%M:%S
