from fastapi import APIRouter
from app.controllers.security_controllers.auth_controller import router as auth_router
from app.controllers.lead_controller import router as leads_router
from app.controllers.lead_field_controller import router as lead_fields_router
from app.controllers.lead_field_type_controller import router as lead_field_types_router
from app.controllers.validation_rule_controller import router as validation_rules_router
from app.controllers.nomenclator_controller import router as nomenclator_router
from app.controllers.nomenclator_item_controller import router as nomenclator_item_router
from app.controllers.campaign_controller import router as campaign_router
from app.controllers.security_controllers.user_controller import router as user_router
from app.controllers.security_controllers.role_controller import router as role_router
from app.controllers.security_controllers.permission_controller import router as permission_router
from app.controllers.workspace_controller import router as workspace_router
from app.controllers.storage_controller import router as storage_router
from app.controllers.lead_field_section_controller import router as lead_field_section_router
from app.controllers.lead_field_subtype_controller import router as lead_field_subtype_router
from app.controllers.template_controller import router as template_router
from app.controllers.search_controller import router as search_router
from app.controllers.import_export_controller import router as import_export_router
from app.controllers.lead_comment_controller import router as lead_comment_router
from app.controllers.organization_controller import router as organization_router
from app.controllers.lead_state_controller import router as lead_state_router
from app.controllers.lead_state_transition_controller import router as lead_state_transition_router
from app.controllers.audit.lead_state_history_controller import router as lead_state_history_router
from app.controllers.lead_flow_controller import router as lead_flow_router
from app.controllers.team_controller import router as team_router
from app.controllers.team_member_controller import router as team_member_router
from app.controllers.team_campaign_access_controller import router as team_campaign_access_router
from app.controllers.team_workspace_access_controller import router as team_workspace_access_router 
from app.controllers.lead_routing_policy_controller import router as lead_routing_rule_policy
from app.controllers.meta_data_controller import router as meta_data_router
from app.controllers.lead_view_controller import router as lead_view_router
from app.controllers.audit.system_audit_log_controller import router as system_audit_log_router
from app.controllers.audit.lead_activity_history_controller import router as lead_activity_history_router
from app.controllers.lead_contact_state_controller import router as lead_contact_state_router
from app.controllers.tag_controller import router as tag_router
from app.controllers.web_form_controller import router as web_form_router
from app.controllers.web_form_public_controller import router as web_form_public_router
from app.controllers.lead_flow_graph_controller import router as lead_flow_graph_router
from app.controllers.field_automation_controller import router as field_automation_router
from app.controllers.dashboard_controller import router as dashboard_router

router = APIRouter()

router.include_router(auth_router)
router.include_router(leads_router)
router.include_router(lead_fields_router)
router.include_router(lead_field_types_router)
router.include_router(validation_rules_router)
router.include_router(nomenclator_router)
router.include_router(nomenclator_item_router)
router.include_router(campaign_router)
router.include_router(user_router)
router.include_router(role_router)
router.include_router(permission_router)
router.include_router(workspace_router)
router.include_router(storage_router)
router.include_router(lead_field_section_router)
router.include_router(lead_field_subtype_router)
router.include_router(template_router)
router.include_router(search_router)
router.include_router(import_export_router)
router.include_router(lead_comment_router)
router.include_router(organization_router)
router.include_router(lead_state_router)
router.include_router(lead_state_transition_router)
router.include_router(lead_state_history_router)
router.include_router(lead_flow_router)
router.include_router(team_router)
router.include_router(team_member_router)
router.include_router(team_campaign_access_router)
router.include_router(team_workspace_access_router)
router.include_router(lead_routing_rule_policy)
router.include_router(meta_data_router)
router.include_router(lead_view_router)
router.include_router(system_audit_log_router)
router.include_router(lead_activity_history_router)
router.include_router(lead_contact_state_router)
router.include_router(tag_router)
router.include_router(web_form_router)
router.include_router(web_form_public_router)
router.include_router(lead_flow_graph_router)
router.include_router(field_automation_router)
router.include_router(dashboard_router)